version: '3'
service:
  nginx:
    image: nginx
    ports: 
      - 443:443
    environment:
  mariadb:
    image: mariadb
    restart: always
    ports:
    environment:
  wordpress:
    image:
    ports:
    environment:
